### ISSUE TITLE
Can't disable `all_on_start`

### ISSUE THREAD

**Issue by amiel** [Driversnote-Dev/guard-erb_lint#1]
Hi, first off, thank you for this project!

I noticed that there is [support for the `all_on_start` option](https://github.com/Driversnote-Dev/guard-erb_lint/blob/master/lib/guard/erb_lint.rb#L31).

However, when processing defaults, the [`||=` sets `options[:all_on_start]`](https://github.com/Driversnote-Dev/guard-erb_lint/blob/master/lib/guard/erb_lint/options.rb#L10) to `true` when originally `false`.

This could probably be resolved by using `fetch` instead of `||=`.

I may submit a PR at some point if no-one else gets to this, but not likely anytime soon.

Thanks again!

**Comment by mathiashsteffensen** [comment]
Thanks for creating this issue, it has now been fixed by [this PR](https://github.com/Driversnote-Dev/guard-erb_lint/pull/2) 👍

**Comment by amiel** [comment]
Thank you!
